/**
 * OAuth providers the generator can't emit — HAND-MAINTAINED. Edit directly.
 *
 * catalog.js is generated by `scripts/sync-providers.js` from the upstream
 * registry and is overwritten on every sync, so nothing hand-written survives
 * there. byok.js is the hand-maintained home for KEY-based providers — but its
 * merge in ./index.js filters on `apiKey.host`, and an OAuth provider has no
 * `apiKey` block, so it cannot live there either. This is the third file: OAuth
 * providers that must be hand-vendored because the registry either does not
 * carry them or carries them under a shape the generator drops.
 *
 * WHY EACH ONE IS HERE rather than generated:
 *
 *  - `kiro` — AWS SSO OIDC device flow with a dynamic-client REGISTER pre-step
 *    (RegisterClient → StartDeviceAuthorization → CreateToken). A single static
 *    `clientId` can't express it: register mints an ephemeral
 *    {clientId, clientSecret} that then feeds BOTH later POSTs. flows.js grew a
 *    `register` step and an `oauthErrors` poll branch (AWS signals "keep polling"
 *    via a 400 BODY code, not an HTTP status) to run it.
 *  - `xai-oauth` / `gitlab-duo` — the OAuth (authorization_code + PKCE) halves of
 *    the paste-only `xai` / `gitlab` registry entries. Their LINK id must equal
 *    the SERVE id (serve does getProvider(account.provider)), and neither split
 *    id exists in the vanilla registry, so the generator can't produce them.
 *
 * These MIRROR apps/api/src/lib/linkCatalog.ts verbatim — the server runs the
 * same link flow, so a drift between the two is a link that works in one place
 * and not the other. Keep them in step.
 *
 * The `transport` block here is read ONLY by probe.js (a node relays blind — the
 * server injects the real transport at serve time), so it carries the omniroute
 * serve address and format for parity but its `auth` is effectively inert. The
 * `oauth` block is what actually drives linking.
 */

/** OpenAI-compatible bearer, shared by reference (see byok.js for why frozen). */
const BEARER = Object.freeze({ combined: true, header: "Authorization", scheme: "bearer" });

/**
 * gitlab-duo is operator-gated: with no GITLAB_DUO_OAUTH_CLIENT_ID configured
 * there is no usable client, so `authorizeUrl`/`clientId` stay undefined and the
 * entry links only once an operator sets the env (mirrors the API's gate). The
 * secret is read only for confidential GitLab apps; a public app omits it.
 */
const GITLAB_DUO_BASE = (process.env.GITLAB_DUO_BASE_URL || "https://gitlab.com").replace(/\/+$/, "");
const GITLAB_DUO_CLIENT_ID = process.env.GITLAB_DUO_OAUTH_CLIENT_ID;
const GITLAB_DUO_CLIENT_SECRET = process.env.GITLAB_DUO_OAUTH_CLIENT_SECRET;

export const OAUTH_EXTRA_PROVIDERS = [
  {
    // AWS SSO OIDC device flow (builder-id, us-east-1). Serving id `kiro`
    // (format "kiro"/CodeWhisperer). The register pre-step mints an ephemeral
    // {clientId, clientSecret} that feeds both the device-authorization and the
    // token POSTs; those + region are carried into the stored credential so
    // refresh can re-POST to the region-scoped OIDC token endpoint.
    id: "kiro",
    name: "Kiro",
    color: "#7C3AED",
    flow: "device",
    oauth: {
      deviceStyle: {
        register: {
          url: "https://oidc.us-east-1.amazonaws.com/client/register",
          method: "POST",
          encoding: "json",
          body: {
            clientName: "kiro-oauth-client",
            clientType: "public",
            scopes: [
              "codewhisperer:completions",
              "codewhisperer:analysis",
              "codewhisperer:conversations",
            ],
            grantTypes: [
              "urn:ietf:params:oauth:grant-type:device_code",
              "refresh_token",
            ],
            issuerUrl: "https://identitycenter.amazonaws.com/ssoins-722374e8c3c8e6c6",
          },
          map: { clientId: "clientId", clientSecret: "clientSecret" },
        },
        initiate: {
          url: "=https://oidc.us-east-1.amazonaws.com/device_authorization",
          method: "POST",
          encoding: "json",
          body: {
            clientId: "@clientId",
            clientSecret: "@clientSecret",
            startUrl: "https://view.awsapps.com/start",
          },
        },
        map: { deviceCode: "deviceCode", userCode: "userCode", verificationUri: "verificationUriComplete", expiresIn: "expiresIn" },
        poll: {
          url: "=https://oidc.us-east-1.amazonaws.com/token",
          method: "POST",
          encoding: "json",
          body: {
            clientId: "@clientId",
            clientSecret: "@clientSecret",
            deviceCode: "@deviceCode",
            grantType: "urn:ietf:params:oauth:grant-type:device_code",
          },
        },
        oauthErrors: true,
        tokenField: "accessToken",
        refreshField: "refreshToken",
        expiresField: "expiresIn",
        region: "us-east-1",
        intervalMs: 5000,
      },
    },
    transport: {
      baseUrl: "https://codewhisperer.us-east-1.amazonaws.com/generateAssistantResponse",
      format: "kiro",
      headers: {
        "Content-Type": "application/json",
        "Accept": "application/vnd.amazon.eventstream",
        "X-Amz-Target": "AmazonCodeWhispererStreamingService.GenerateAssistantResponse",
        "User-Agent": "AWS-SDK-JS/3.0.0 kiro-ide/1.0.0",
        "X-Amz-User-Agent": "aws-sdk-js/3.0.0 kiro-ide/1.0.0",
      },
      auth: BEARER,
    },
    models: [
      "claude-sonnet-5",
      "claude-sonnet-4.5",
      "claude-haiku-4.5",
      "deepseek-3.2",
      "minimax-m2.5",
      "minimax-m2.1",
      "glm-5",
      "qwen3-coder-next",
      "gpt-5.6-sol",
      "gpt-5.6-terra",
      "gpt-5.6-luna",
    ],
  },
  {
    // OAuth (authorization_code + PKCE) half of xAI. Serving id `xai-oauth`
    // (api.x.ai, format openai — serves through the gate with no translator).
    // grok's public client bakes in a FIXED loopback redirect
    // (http://127.0.0.1:56121/callback), so this links CLI-only (aile.sh binds
    // the loopback listener). Public PKCE client → no clientSecret.
    id: "xai-oauth",
    name: "xAI (Grok) OAuth",
    color: "#111827",
    flow: "authcode",
    oauth: {
      clientId: "b1a00492-073a-47ea-816f-4c329264a828",
      authorizeUrl: "https://auth.x.ai/oauth2/authorize",
      tokenUrl: "https://auth.x.ai/oauth2/token",
      scope: "openid profile email offline_access grok-cli:access api:access",
      codeChallengeMethod: "S256",
      fixedPort: 56121,
      callbackPath: "/callback",
      extraParams: { plan: "generic", referrer: "cli-proxy-api" },
    },
    transport: {
      baseUrl: "https://api.x.ai/v1/chat/completions",
      format: "openai",
      auth: BEARER,
    },
    models: [
      "grok-4.5",
      "grok-4.3",
      "grok-build-0.1",
      "grok-4.20-multi-agent-0309",
      "grok-4.20-0309-reasoning",
      "grok-4.20-0309-non-reasoning",
    ],
  },
  {
    // OAuth (authorization_code + PKCE) half of GitLab Duo. Serving id
    // `gitlab-duo` (code-suggestions completions, needs the serve translator).
    // Operator-gated on GITLAB_DUO_OAUTH_CLIENT_ID: absent env leaves clientId /
    // authorizeUrl undefined, so linking stays off until the operator sets it.
    id: "gitlab-duo",
    name: "GitLab Duo (OAuth)",
    color: "#FC6D26",
    flow: "authcode",
    oauth: {
      clientId: GITLAB_DUO_CLIENT_ID,
      clientSecret: GITLAB_DUO_CLIENT_SECRET,
      authorizeUrl: GITLAB_DUO_CLIENT_ID ? `${GITLAB_DUO_BASE}/oauth/authorize` : undefined,
      tokenUrl: `${GITLAB_DUO_BASE}/oauth/token`,
      scope: "ai_features read_user",
      codeChallengeMethod: "S256",
    },
    transport: {
      baseUrl: "https://gitlab.com/api/v4/code_suggestions/completions",
      format: "openai",
      auth: BEARER,
    },
    models: [
      "claude-sonnet-4-6",
      "claude-haiku-4-5",
    ],
  },
];

/** Ids in this file, for the merge in ./index.js to detect a generated shadow. */
export const OAUTH_EXTRA_IDS = OAUTH_EXTRA_PROVIDERS.map((p) => p.id);
