/**
 * GENERATED by scripts/pin-llamacpp.js — do not edit by hand.
 *
 * The llama.cpp build `aile local` installs, with each archive's sha256 as
 * GitHub publishes it. A download that does not match is deleted and refused.
 * Release: https://github.com/ggml-org/llama.cpp/releases/tag/b11320 (2026-10-01)
 */

export const LLAMACPP_PINS = {
  "tag": "b11320",
  "assets": {
    "win-x64-cpu": {
      "file": "llama-b11320-bin-win-cpu-x64.zip",
      "size": 19275015,
      "sha256": "20661e00d6e7a98cecf87342af12d6bf836803229000cf19b338521273bd1fc1"
    },
    "win-x64-vulkan": {
      "file": "llama-b11320-bin-win-vulkan-x64.zip",
      "size": 33208164,
      "sha256": "20e11c93085112d15bad9716531954c6752024c023153c96b493349041ae5779"
    },
    "win-x64-cuda": {
      "file": "llama-b11320-bin-win-cuda-12.4-x64.zip",
      "size": 263401101,
      "sha256": "f6c0cbfe03763136ed7744d1b4d12fe085534153b3d2f0fabd2edc0dddcf4977",
      "extra": {
        "file": "cudart-llama-bin-win-cuda-12.4-x64.zip",
        "size": 391443627,
        "sha256": "8c79a9b226de4b3cacfd1f83d24f962d0773be79f1e7b75c6af4ded7e32ae1d6"
      },
      "minDriver": "551.61"
    },
    "win-arm64-cpu": {
      "file": "llama-b11320-bin-win-cpu-arm64.zip",
      "size": 12117796,
      "sha256": "6d4fc02dd3e45d3ebd919e098bff317b9bc06879476d79ae725be9522de9311d"
    },
    "macos-arm64": {
      "file": "llama-b11320-bin-macos-arm64.tar.gz",
      "size": 11827796,
      "sha256": "f6f337fc7d2ff9260f53177cf4fe6bbf6b0f7faa75a49fb224aaf66885a5c956"
    },
    "macos-x64": {
      "file": "llama-b11320-bin-macos-x64.tar.gz",
      "size": 11384588,
      "sha256": "ca6d7198ac258466ec109ef81fd0700467758218a74a4736936876c56e7ff1d1"
    },
    "linux-x64-cpu": {
      "file": "llama-b11320-bin-ubuntu-x64.tar.gz",
      "size": 17544875,
      "sha256": "ef1856938dc1434138ce53688791eb0d2d64cf46e309a0942a12bba3366c0919"
    },
    "linux-x64-vulkan": {
      "file": "llama-b11320-bin-ubuntu-vulkan-x64.tar.gz",
      "size": 31492038,
      "sha256": "5fb648c3fd7ea35e4a4a05b53db6a82e1f10e049c6cfc22845d7c6c3481e454b"
    },
    "linux-x64-cuda": {
      "file": "llama-b11320-bin-ubuntu-cuda-12.8-x64.tar.gz",
      "size": 171370437,
      "sha256": "0e1ff5490869eef0479f95df094bdc75d87890882f687d3d537192eefff87861",
      "extra": {
        "file": "cudart-llama-b11320-bin-ubuntu-cuda-12.8-x64.tar.gz",
        "size": 594377651,
        "sha256": "8c32c1c07568395f84bd8b308293c889bad775037f82a7423dede6900827e42a"
      },
      "minDriver": "570.26"
    },
    "linux-arm64-cpu": {
      "file": "llama-b11320-bin-ubuntu-arm64.tar.gz",
      "size": 13590823,
      "sha256": "88589b963d8e2ffd2d4df2f542ed7e301fb636b637c99081f5d58646aee20a9a"
    }
  }
};
